apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: device-registry
  version:  0.1.0
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: test
  source:
    path: charts/test-app
    repoURL: https://github.com/openshift-app-service-poc/test-apps.git
    targetRevision: HEAD
    helm:
      values: |
        image:
          tag: latest
        ingress:
          host: test-app.$INGRESS.xip.io
      version: v3
  destination:
    namespace: test-station
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true